---
name: Release Images

on:
  workflow_dispatch:
  push:
    branches:
      - devel
      - release-*

permissions: {}

jobs:
  release:
    name: Release Images
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 0

      - name: Build and release new images
        uses: submariner-io/shipyard/gh-actions/release-images@devel
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
