---
name: Reporting

on:
  push:
    branches:
      - devel
      - release-*

permissions: {}

jobs:
  unit-coverage:
    name: Go Unit Test Coverage
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
        with:
          fetch-depth: 0

      - name: Run Go unit tests
        run: make unit

      - name: Run SonarScan, upload Go test results and coverage
        uses: sonarsource/sonarcloud-github-action@383f7e52eae3ab0510c3cb0e7d9d150bbaeab838
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  variant-analysis:
    name: Variant Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Initialize CodeQL
        uses: github/codeql-action/init@f779452ac5af1c261dce0346a8f964149f49322b
        with:
          languages: go
      - name: Run CodeQL variant analysis
        uses: github/codeql-action/analyze@f779452ac5af1c261dce0346a8f964149f49322b
      - name: Show CodeQL scan SARIF report
        if: always()
        run: cat ../results/go.sarif

  vulnerability-scan:
    name: Vulnerability Scanning
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871
      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@49e50b215b647c5ec97abb66f69af73c46a4ca08
        id: scan
        with:
          path: "."
          fail-build: false
      - name: Show Anchore scan SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
