---
name: Twitter

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: gr2m/twitter-together@01d858fb16f42c1840348f788c6d2fd31f4465c9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Tweet
        uses: gr2m/twitter-together@01d858fb16f42c1840348f788c6d2fd31f4465c9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
